/**
 * Emotion Daily Report Page
 */

import { observer } from 'mobx-react-lite'
import { useTranslation } from 'react-i18next'
import { useQueryParams } from '@/hooks/useUrlParams'
import { Moon } from 'lucide-react'
import { DailyScoreCard } from '@/components/common/DailyScoreCard'
import { AIInsightsCard } from '@/components/common/AIInsightsCard'
import { SuggestionsList } from '@/components/common/SuggestionsList'
import {
    EmotionProportionChart,
    EmotionDistributionCard,
} from '@/modules/daily/emotion'
import { EMOTION_COLORS, UI_STYLES } from '@/config/theme'
import { useEmotionDailyData } from '@/hooks/useDailyData'

function EmotionDailyPage() {
    const { t } = useTranslation()
    const params = useQueryParams()
    const dateParam = params.date
    const { data, isLoading, isError, error } = useEmotionDailyData(dateParam || undefined)

    if (isLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: '#F1EFEE' }}>
                <div className="animate-pulse text-slate-500">Loading...</div>
            </div>
        )
    }

    if (isError) {
        return (
            <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: '#F1EFEE' }}>
                <div className="text-red-500">Error: {error?.message || 'Failed to load data'}</div>
            </div>
        )
    }

    if (!data) return null

    return (
        <div className="min-h-screen pb-20" style={{ backgroundColor: '#F1EFEE' }}>
            <div className={`${UI_STYLES.pageMaxWidth} mx-auto`}>
                <div className="p-4 space-y-4">
                    {/* Score Card */}
                    <DailyScoreCard
                        score={data.score}
                        maxScore={100}
                        levelLabel={data.levelLabel}
                        percentile={data.percentile}
                        percentileMessage={data.percentileMessage}
                        aiTags={data.aiTags}
                        themeColor="#FFD12D"
                        gradientEndColor="#FF9D03"
                        title={t('daily.todayEmotionScore', "Today's emotion score")}
                        icon={<Moon className="w-6 h-6 text-white" />}
                    />

                    {/* Emotion Proportion Chart */}
                    <EmotionProportionChart data={data.chart} />

                    {/* Emotion Distribution */}
                    <EmotionDistributionCard
                        mainEmotion={data.distribution.mainEmotion}
                        mainEmotionLabel={data.distribution.mainEmotionLabel}
                        items={data.distribution.items}
                    />

                    {/* AI Insights */}
                    {data.aiInsights.length > 0 && (
                        <AIInsightsCard
                            insights={data.aiInsights}
                            themeColor={EMOTION_COLORS.primary}
                        />
                    )}

                    {/* Suggestions */}
                    <SuggestionsList suggestions={data.suggestions || []} />

                    {/* Disclaimer */}
                    <p className="text-xs text-slate-400 text-center px-4 py-2">
                        {t('common.disclaimer', 'The monitoring results of this product are for reference only. Some content is generated by AI, so please verify carefully. It should not be used for medical diagnosis. If you feel unwell, please seek medical attention promptly.')}
                    </p>
                </div>
            </div>
        </div>
    )
}

export default observer(EmotionDailyPage)
