/**
 * Emotion Daily Report Page
 */

import { useState, useEffect, useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { Moon } from 'lucide-react'
import { DailyScoreCard } from '@/components/common/DailyScoreCard'
import { AIInsightsCard } from '@/components/common/AIInsightsCard'
import { SuggestionsList } from '@/components/common/SuggestionsList'
import {
    EmotionProportionChart,
    EmotionDistributionCard,
    generateEmotionDemoData,
    isDemoModeEnabled,
    toggleDemoMode,
    type EmotionDailyData,
} from '@/daily/emotion'
import { EMOTION_COLORS } from '@/config/theme'

export default function EmotionDailyPage() {
    const { t } = useTranslation()
    const [data, setData] = useState<EmotionDailyData | null>(null)
    const [demoMode, setDemoMode] = useState(isDemoModeEnabled())

    // Load data
    useEffect(() => {
        // For now, use demo data
        setData(generateEmotionDemoData())
    }, [demoMode])

    const handleToggleDemo = () => {
        const newState = toggleDemoMode()
        setDemoMode(newState)
    }

    if (!data) {
        return <div className="flex items-center justify-center h-64">Loading...</div>
    }

    return (
        <div className="min-h-screen pb-20" style={{ backgroundColor: '#F1EFEE' }}>
            <div className="max-w-2xl mx-auto">
                <div className="p-4 space-y-4">
                    {/* Demo mode toggle */}
                    <div className="flex items-center justify-end gap-2">
                        <span className="text-xs text-slate-500">Demo Mode</span>
                        <button
                            onClick={handleToggleDemo}
                            className={`w-10 h-5 rounded-full transition-colors ${demoMode ? 'bg-orange-400' : 'bg-slate-300'
                                }`}
                        >
                            <span
                                className={`block w-4 h-4 bg-white rounded-full shadow transform transition-transform ${demoMode ? 'translate-x-5' : 'translate-x-0.5'
                                    }`}
                            />
                        </button>
                    </div>

                    {/* Score Card */}
                    <DailyScoreCard
                        score={data.score}
                        maxScore={100}
                        levelLabel={data.levelLabel}
                        percentile={data.percentile}
                        percentileMessage={data.percentileMessage}
                        aiTags={data.aiTags}
                        themeColor="#FFD12D"
                        gradientEndColor="#FF9D03"
                        title={t('daily.todayEmotionScore', "Today's emotion score")}
                        icon={<Moon className="w-6 h-6 text-white" />}
                    />

                    {/* Emotion Proportion Chart */}
                    <EmotionProportionChart data={data.chart} />

                    {/* Emotion Distribution */}
                    <EmotionDistributionCard
                        mainEmotion={data.distribution.mainEmotion}
                        mainEmotionLabel={data.distribution.mainEmotionLabel}
                        items={data.distribution.items}
                    />

                    {/* AI Insights */}
                    {data.aiInsights.length > 0 && (
                        <AIInsightsCard
                            insights={data.aiInsights}
                            themeColor={EMOTION_COLORS.primary}
                        />
                    )}

                    {/* Suggestions */}
                    {data.suggestions.length > 0 && (
                        <SuggestionsList suggestions={data.suggestions} />
                    )}

                    {/* Disclaimer */}
                    <p className="text-xs text-slate-400 text-center px-4 py-2">
                        {t('common.disclaimer', 'The monitoring results of this product are for reference only. Some content is generated by AI, so please verify carefully. It should not be used for medical diagnosis. If you feel unwell, please seek medical attention promptly.')}
                    </p>
                </div>
            </div>
        </div>
    )
}
